<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>exitecho</AssemblyName>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExitEcho.Core\ExitEcho.Core.csproj" />
  </ItemGroup>
</Project>
